### ISSUE TITLE
无法修改用户名和更改每月每次送花数

### ISSUE THREAD

**Issue by dengwentong** [wozien/team-flower#6]
**无法修改用户名和更改每月每次送花数**
修改用户名，一直提示用户名不能为空，修改最多每次送花数，无法保存到数据库。手动新建maxConsume字段，可以识别。

**Comment by venkate123** [comment]
@dengwentong 请问你解决了吗？此外我也不能创建团队，点了之后没有反应，不知道为什么。

**Comment by wozien** [comment]
> @dengwentong 请问你解决了吗？此外我也不能创建团队，点了之后

**Comment by wozien** [comment]
> @dengwentong 请问你解决了吗？此外我也不能创建团队，点了之后没有反应，不知道为什么。

应该腾讯云开发改成收费了，由于未及时迁移，所有该小程序暂时关闭了

**Comment by dengwentong** [comment]
> @dengwentong 请问你解决了吗？此外我也不能创建团队，点了之后没有反应，不知道为什么。

我是自己重写了方法。勉强可以实现。我现在新加同事比较麻烦。无法自动获取用户信息和头像，应当是仓库里的程序在获取用户信息的时候采用了老的接口。目前腾讯貌似换接口了。
我目前采用手动添加 OpenID的方式。🤣😂
